### ISSUE TITLE
Unable to run gst-top-1.0

### ISSUE THREAD

**Issue by accordionman** [kirushyk/gst-instruments#21]
Hi,
I'm not able to run the core command gst-top-1.0 for any pipeline. Any time I run it the result is always the same:

gst-play-1.0: symbol lookup error: /usr/local/lib/libgstintercept.so.0: undefined symbol: for_each_buffer
** (gst-top-1.0:23818): WARNING **: gst-play-1.0 exited with code 32512

Could you please help me how to solve this?
Thx;-)

**Comment by kirushyk** [comment]
For me it looks like this:
`
$ gst-top-1.0 gst-play-1.0 ~/Music/joke.mp3 
dyld: Symbol not found: _for_each_buffer
  Referenced from: /usr/local/lib/libgstintercept.dylib
  Expected in: flat namespace
 in /usr/local/lib/libgstintercept.dylib

** (gst-top-1.0:6362): WARNING **: gst-play-1.0 exited with code 11
$
`

**Comment by kirushyk** [comment]
Sorry about that :-)

**Comment by kirushyk** [comment]
Works good now?

**Comment by accordionman** [comment]
Yes, everything is fine now! Thanks, best regards;-) Very good utility I think...
