### ISSUE TITLE
how to install this 

### ISSUE THREAD

**Issue by kingalione** [kirushyk/gst-instruments#22]
I'm trying to install this application but I don't know how to install this on a linux machine. 

I tried with automake and autoconf but nothing worked correctly. I always get many errors on this like here:

    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
configure.ac:5: error: required file './compile' not found
configure.ac:5:   'automake --add-missing' can install 'compile'
configure.ac:6: error: required file './config.guess' not found
configure.ac:6:   'automake --add-missing' can install 'config.guess'
configure.ac:6: error: required file './config.sub' not found
configure.ac:6:   'automake --add-missing' can install 'config.sub'
configure.ac:14: error: required file './install-sh' not found
configure.ac:14:   'automake --add-missing' can install 'install-sh'
configure.ac:6: error: required file './ltmain.sh' not found
configure.ac:40: error: required file './missing' not found
configure.ac:40:   'automake --add-missing' can install 'missing'

Can you please update the readme so people can follow the installation instructions?

**Comment by kirushyk** [comment]
Can you please show what command do you type and what this output is for.
Installation instructions is common (just like for any other autotools-based package):

    ./autogen.sh
    make
    sudo make install

**Comment by kingalione** [comment]
Ok when I run make (after successfully running ./autogen.sh) I get this error:

$ make
make  all-recursive
make[1]: Entering directory `/home/chronext/gst-instruments'
Making all in tools
make[2]: Entering directory `/home/chronext/gst-instruments/tools'
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -g -O2 -MT gst_top_1.0-gst-top.o -MD -MP -MF .deps/gst_top_1.0-gst-top.Tpo -c -o gst_top_1.0-gst-top.o `test -f 'gst-top.c' || echo './'`gst-top.c
gst-top.c: In function 'main':
gst-top.c:39:10: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
   system ("rm -f " GST_TOP_TRACE_FILENAME_BASE ".gsttrace");
          ^
gst-top.c:69:12: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
     system (BINDIR "/gst-report-1.0 " GST_TOP_TRACE_FILENAME_BASE ".gsttrace");
            ^
mv -f .deps/gst_top_1.0-gst-top.Tpo .deps/gst_top_1.0-gst-top.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -g -O2   -o gst-top-1.0 gst_top_1.0-gst-top.o -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0   
libtool: link: gcc -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DLIBDIR=\"/usr/local/lib\" -DBINDIR=\"/usr/local/bin\" -g -O2 -o gst-top-1.0 gst_top_1.0-gst-top.o  -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -pthread
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DDATADIR='"/usr/local/share"' -g -O2 -MT gst_report_1.0-gst-report.o -MD -MP -MF .deps/gst_report_1.0-gst-report.Tpo -c -o gst_report_1.0-gst-report.o `test -f 'gst-report.c' || echo './'`gst-report.c
mv -f .deps/gst_report_1.0-gst-report.Tpo .deps/gst_report_1.0-gst-report.Po
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DDATADIR='"/usr/local/share"' -g -O2 -MT gst_report_1.0-formatters.o -MD -MP -MF .deps/gst_report_1.0-formatters.Tpo -c -o gst_report_1.0-formatters.o `test -f 'formatters.c' || echo './'`formatters.c
mv -f .deps/gst_report_1.0-formatters.Tpo .deps/gst_report_1.0-formatters.Po
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DDATADIR='"/usr/local/share"' -g -O2 -MT ../libs/gst/trace/gst_report_1.0-gstgraveyard.o -MD -MP -MF ../libs/gst/trace/.deps/gst_report_1.0-gstgraveyard.Tpo -c -o ../libs/gst/trace/gst_report_1.0-gstgraveyard.o `test -f '../libs/gst/trace/gstgraveyard.c' || echo './'`../libs/gst/trace/gstgraveyard.c
../libs/gst/trace/gstgraveyard.c: In function 'gst_graveyard_pick_element_enter':
../libs/gst/trace/gstgraveyard.c:107:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (GList *iterator = graveyard->enters; iterator != NULL; iterator = iterator->next) {
   ^
../libs/gst/trace/gstgraveyard.c:107:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [../libs/gst/trace/gst_report_1.0-gstgraveyard.o] Error 1
make[2]: Leaving directory `/home/chronext/gst-instruments/tools'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/chronext/gst-instruments'
make: *** [all] Error 2

**Comment by kirushyk** [comment]
It looks like `configure.ac` should check for C99 support.

**Comment by kingalione** [comment]
I'm not very familiar with compiling c++ code so what does that mean to me?

**Comment by kirushyk** [comment]
I added `AC_PROG_CC_STDC` to `configure.ac`. Try now.

**Comment by kingalione** [comment]
I pulled your changes, run ./autogen.sh again and run make again with the same result:

```
~/gst-instruments$ make
make  all-recursive
make[1]: Entering directory `/home/chronext/gst-instruments'
Making all in tools
make[2]: Entering directory `/home/chronext/gst-instruments/tools'
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DDATADIR='"/usr/local/share"' -g -O2 -MT ../libs/gst/trace/gst_report_1.0-gstgraveyard.o -MD -MP -MF ../libs/gst/trace/.deps/gst_report_1.0-gstgraveyard.Tpo -c -o ../libs/gst/trace/gst_report_1.0-gstgraveyard.o `test -f '../libs/gst/trace/gstgraveyard.c' || echo './'`../libs/gst/trace/gstgraveyard.c
../libs/gst/trace/gstgraveyard.c: In function 'gst_graveyard_pick_element_enter':
../libs/gst/trace/gstgraveyard.c:107:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (GList *iterator = graveyard->enters; iterator != NULL; iterator = iterator->next) {
   ^
../libs/gst/trace/gstgraveyard.c:107:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [../libs/gst/trace/gst_report_1.0-gstgraveyard.o] Error 1
make[2]: Leaving directory `/home/chronext/gst-instruments/tools'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/chronext/gst-instruments'
make: *** [all] Error 2
```

**Comment by kirushyk** [comment]
Let's try with `AC_PROG_CC_C99` :-)

**Comment by kingalione** [comment]
This time a deleted the dir, cloned it again and started the installation after checking if the changes you made are inside the repo. 

After running make I get again the same error:

```
~/gst-instruments$ make
make  all-recursive
make[1]: Entering directory `/home/chronext/gst-instruments'
Making all in tools
make[2]: Entering directory `/home/chronext/gst-instruments/tools'
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -g -O2 -MT gst_top_1.0-gst-top.o -MD -MP -MF .deps/gst_top_1.0-gst-top.Tpo -c -o gst_top_1.0-gst-top.o `test -f 'gst-top.c' || echo './'`gst-top.c
gst-top.c: In function 'main':
gst-top.c:39:10: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
   system ("rm -f " GST_TOP_TRACE_FILENAME_BASE ".gsttrace");
          ^
gst-top.c:69:12: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
     system (BINDIR "/gst-report-1.0 " GST_TOP_TRACE_FILENAME_BASE ".gsttrace");
            ^
mv -f .deps/gst_top_1.0-gst-top.Tpo .deps/gst_top_1.0-gst-top.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DLIBDIR='"/usr/local/lib"' -DBINDIR='"/usr/local/bin"' -g -O2   -o gst-top-1.0 gst_top_1.0-gst-top.o -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0   
libtool: link: gcc -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DLIBDIR=\"/usr/local/lib\" -DBINDIR=\"/usr/local/bin\" -g -O2 -o gst-top-1.0 gst_top_1.0-gst-top.o  -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -pthread
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DDATADIR='"/usr/local/share"' -g -O2 -MT gst_report_1.0-gst-report.o -MD -MP -MF .deps/gst_report_1.0-gst-report.Tpo -c -o gst_report_1.0-gst-report.o `test -f 'gst-report.c' || echo './'`gst-report.c
mv -f .deps/gst_report_1.0-gst-report.Tpo .deps/gst_report_1.0-gst-report.Po
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DDATADIR='"/usr/local/share"' -g -O2 -MT gst_report_1.0-formatters.o -MD -MP -MF .deps/gst_report_1.0-formatters.Tpo -c -o gst_report_1.0-formatters.o `test -f 'formatters.c' || echo './'`formatters.c
mv -f .deps/gst_report_1.0-formatters.Tpo .deps/gst_report_1.0-formatters.Po
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -DDATADIR='"/usr/local/share"' -g -O2 -MT ../libs/gst/trace/gst_report_1.0-gstgraveyard.o -MD -MP -MF ../libs/gst/trace/.deps/gst_report_1.0-gstgraveyard.Tpo -c -o ../libs/gst/trace/gst_report_1.0-gstgraveyard.o `test -f '../libs/gst/trace/gstgraveyard.c' || echo './'`../libs/gst/trace/gstgraveyard.c
../libs/gst/trace/gstgraveyard.c: In function 'gst_graveyard_pick_element_enter':
../libs/gst/trace/gstgraveyard.c:107:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (GList *iterator = graveyard->enters; iterator != NULL; iterator = iterator->next) {
   ^
../libs/gst/trace/gstgraveyard.c:107:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [../libs/gst/trace/gst_report_1.0-gstgraveyard.o] Error 1
make[2]: Leaving directory `/home/chronext/gst-instruments/tools'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/chronext/gst-instruments'
make: *** [all] Error 2
```

**Comment by kirushyk** [comment]
Try `CC="gcc -std=gnu99" ./autogen.sh` then, instead of just `./autogen.sh`.

**Comment by kingalione** [comment]
It helped but now I get this one:

```
In file included from gstinstruments.c:20:0:
gstinstruments.h:5:27: fatal error: gst/gsttracer.h: No such file or directory
 #include <gst/gsttracer.h>
                           ^
compilation terminated.
make[2]: *** [libgstinstruments_la-gstinstruments.lo] Error 1
make[2]: Leaving directory `/home/chronext/gst-instruments/plugins/tracers'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/chronext/gst-instruments'
make: *** [all] Error 2
```

**Comment by kirushyk** [comment]
It looks like you use old GStreamer, let's get rid of that module in case there is no tracing subsystem present in current installation.

Use something like `printf "all:\ninstall:\nclean:\nuninstall:\n" > plugins/tracers/Makefile` as workaround step between `./autogen.sh` and `make`. I will fix that in next few days.

**Comment by Triuman** [comment]
I'm having the same problem as @kingalione 

I'm trying install this on Jessie Lite of Raspberry Pi 3. I'm using Gstreamer 1.4.4

Your workaround didn't work for me. Could you please help me to install the program?

Thank you.

**Comment by kirushyk** [comment]
Sure, how can I help you?

**Comment by development-1000realities** [comment]
I also had a problem installing, managed to solve it but in case anyone needs this:
**OS:** 
Ubuntu 16.04 LTS
**Problem:**
./autogen.sh says it cannot find libtool but apt-get says that libtool is installed
**Solution:**
sudo apt-get install libtool-bin

**Comment by kirushyk** [comment]
Now you can use Meson build system to compile and install this.
