### ISSUE TITLE
Move to gst-devtools

### ISSUE THREAD

**Issue by thiblahute** [kirushyk/gst-instruments#27]
I think big parts of that tool would have their place in [gst-devtools](https://cgit.freedesktop.org/gstreamer/gst-devtools), and the tracer itself might be moved to -core (not sure, I have not check the code well enough yet).

What do you think about that? I can handle the move if you agree about it.

**Comment by kirushyk** [comment]
Hello Thibault, we can discuss this.
However, I think this will require some effort from me and at this moment I can't dedicate much time.
