### ISSUE TITLE
Any ETA on the next (0.2.4) release?

### ISSUE THREAD

**Issue by rib0s0me** [kirushyk/gst-instruments#33]

**Comment by kirushyk** [comment]
Any requirements or wishes to implement?

**Comment by rib0s0me** [comment]
None as of now, however it's almost been a year since the last release and there seem to be some crash fixes that have gone in since.

**Comment by kirushyk** [comment]
Sorry, I wasn't able to dedicate time for this. I have no any plan at this moment. You are free to make fixes. I will return to this as soon as I will have more time.

**Comment by kirushyk** [comment]
Take a look please, GStreamer Instruments were ported to Meson build.
