### ISSUE TITLE
playbin3 not work ?

### ISSUE THREAD

**Issue by rolandjon** [kirushyk/gst-instruments#34]
playbin2 work well,
---
gst-top-1.0 gst-launch-1.0 playbin uri=http://10.9.44.116/vod/ts/1080p/1080p.ts
gst-instruments-1.0 gst-top.gsttrace
---
playbin3 not work
----
gst-top-1.0 gst-launch-1.0 playbin3 uri=http://10.9.44.116/vod/ts/1080p/1080p.ts
gst-instruments-1.0 gst-top.gsttrace

Error: <stdin>: syntax error in line 1 near '('
Error: <stdin>: syntax error in line 1 near '('
Error: <stdin>: syntax error in line 1 near '('
Error: <stdin>: syntax error in line 1 near '('
Error: <stdin>: syntax error in line 1 near '('
Error: <stdin>: syntax error in line 1 near '('
Error: <stdin>: syntax error in line 1 near '('
----

**Comment by kirushyk** [comment]
I can not open that TS file.

**Comment by kirushyk** [comment]
Playbin3 works for me.
