### ISSUE TITLE
couldn't find task error

### ISSUE THREAD

**Issue by milianw** [kirushyk/gst-instruments#44]
I've recorded some trace data but I cannot visualize the data file, all I get is:

```
gst-report-1.0 pipeline0.gsttrace 
couldn't find task 0x78696d01e12048

(gst-report-1.0:71207): GLib-CRITICAL **: 19:03:11.589: g_array_free: assertion 'array' failed
could not read trace file: pipeline0.gsttrace
```

Here's the recorded trace file (compressed) that triggers this issue:

[pipeline0.gsttrace.gz](https://github.com/kirushyk/gst-instruments/files/3865361/pipeline0.gsttrace.gz)

**Comment by kirushyk** [comment]
A lot of data is missing in your trace file. It is little you can fetch from it. But I made tool tolerate absence of task records.
