### ISSUE TITLE
Linkage error

### ISSUE THREAD

**Issue by eshiva0** [kirushyk/gst-instruments#45]
Getting below error while executing "gst-top-1.0 gst-launch-1.0 videotestsrc ! glimagesink"
CANNOT LINK EXECUTABLE "gst-launch-1.0": library "/home/xxx/xxx/xxx/lib/libgstintercept.so.0" not found

** (gst-top-1.0:11500): WARNING **: gst-launch-1.0 exited with code 256

Also I don't find file with "libgstintercept.so.0" anyware .
Please help.

**Comment by ribalda** [comment]
libgstintercept.so.0 is part of this project. Did you run the installation?

**Comment by eshiva0** [comment]
I am integrating this on Android OS. Al lmy gstreamer code is compiled using sources. I even get below errors while compiling so I skipped instrument for now and compiled only gst-top.
gstinstruments.c:57: error: undefined reference to 'gst_trace_new'
gstinstruments.c:313: error: undefined reference to 'trace_heir'
gstinstruments.c:314: error: undefined reference to 'dump_hierarchy_info_if_needed'
gstinstruments.c:171: error: undefined reference to 'get_source_pad'
gstinstruments.c:173: error: undefined reference to 'trace_heir'
gstinstruments.c:176: error: undefined reference to 'mach_thread_self'
gstinstruments.c:177: error: undefined reference to 'get_cpu_time'
gstinstruments.c:182: error: undefined reference to 'gst_trace_element_entered_entry_new'
gstinstruments.c:183: error: undefined reference to 'current_monotonic_time'
gstinstruments.c:183: error: undefined reference to 'gst_trace_entry_set_timestamp'
gstinstruments.c:184: error: undefined reference to 'gst_trace_entry_set_pipeline'
gstinstruments.c:185: error: undefined reference to 'gst_trace_entry_set_thread_id'
gstinstruments.c:186: error: undefined reference to 'gst_trace_element_entered_entry_set_upstack_element'
gstinstruments.c:187: error: undefined reference to 'gst_trace_element_entered_entry_set_downstack_element'
gstinstruments.c:188: error: undefined reference to 'gst_trace_element_entered_entry_set_enter_time'

**Comment by eshiva0** [comment]
I am running below commands on Android-P.

echo "./autogen.sh --prefix $GST_PREPACKAGE --libdir $GST_PREPACKAGE/lib/ --program-prefix= --host=arm-linux-androideabi" > build.sh
chmod +x ./build.sh &&  ./build.sh && make install -j$(nproc)

below is the build output:
+ ./build.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:8: installing './compile'
configure.ac:44: installing './missing'
instruments/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
++ nproc
+ make install -j4
make: *** No rule to make target 'install'.  Stop.
+ exit 1
ninja: build stopped: subcommand failed.

**Comment by kirushyk** [comment]
When you compiled gst-instruments from sources, did you install libgstintercept.so to some location on your device?

**Comment by eshiva0** [comment]
Yes I did. Otherwise I was getting different error. After that I started seeing, this so.0 missing error message (libgstintercept.so.0" not found). But again, this is after I stopped compiling plugins folder code as with this I was getting compilation errors.
Also I tried with another branch (fix29) but with this configure it self is failing on Android. Not sure what is the problem. Please refer my last comment for the error output.

**Comment by eshiva0** [comment]
Can you please look into this.
-> is "libgstinstruments.so" is needed for any executable like gst-top or gst-report?
-> It looks "make install" is failing in my case if I stop compiling plugins folder. In runtime I am getting this error. How to generate "libgstintercept.so.0" file.
libgstintercept.so.0  not found
-> I simply tried by creating a copy of "libgstintercept.so" to "libgstintercept.so.0" but it thrown below error.
/gst-top-1.0 gst-launch-1.0 videotestsrc ! fakesink                           <
CANNOT LINK EXECUTABLE "sh": "/system/lib/libgstintercept.so.0" is 32-bit instead of 64-bit
