### ISSUE TITLE
unable to find gst-instrument-1.0 binary

### ISSUE THREAD

**Issue by sauravkumar-volt** [kirushyk/gst-instruments#52]
Hi,
I am trying to run `gst-instrument-1.0` on Linux 20.04, x86_64  system but I get a response back saying
`gst-instrument-1.0: command not found` 

I am able to create trace file, view them using cmd,
```gst-report-1.0 --dot pipeline0.gsttrace | dot -Tsvg > perf.svg```
but not able to run using
```gst-instruments-1.0 pipeline0.gsttrace```

I didn't find any binary for `gst-instrument-1.0` except the lib `libgstinstruments.so`

**Comment by kirushyk** [comment]
Please check whether UI component was build. I think you need GTK and Vala as deps.

**Comment by sauravkumar-volt** [comment]
Thank You so much for your swift response.
I was missing vala compiler. :)
